# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fujimakishouten/debian-stretch64"
  config.vm.define "fastimagingvm" do |fastimagingvm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 3
  end

  config.vm.provision "shell",
    inline: "sudo apt-get install -y python-minimal"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision_and_build.yml"
    ansible.verbose = "vv"
    ansible.groups = {"test" => ["fastimagingvm"]}
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
