#ifndef IMAGER_H
#define IMAGER_H

// STP library includes
#include "../common/fft.h"
#include "../gridder/gridder.h"
#include <cblas.h>

#define arc_sec_to_rad(value) ((value / 3600.0) * (M_PI / 180.0))

namespace stp {

const double image_slice = 0;
const double beam_slice = 1;

typedef enum { FFTW,
    ARMAFFT } fft_function_type;

/**
 * @brief image_visibilities function
 *
 * This function (template + functor) create a two arrays representing the image map and beam model.
 *
 * @param[in] vis (cx_mat): Complex visibilities
 * @param[in] uvw_lambda (cx_mat): UVW-coordinates of visibilities. Units are multiples of wavelength.
 * @param[in] image_size (int): Width of the image in pixels
 * @param[in] cell_size (double): Angular-width of a synthesized pixel in the image to be created
 * @param[in] support (double): Defines the 'radius' of the bounding box within which convolution takes place.
 * @param[in] kernel_exact (bool): Calculate exact kernel-values for every UV-sample.
 * @param[in] oversampling (int): Controls kernel-generation if 'kernel_exact == False'. Larger values give a finer-sampled set of pre-cached kernels.
 * @param[in] normalize (bool): Whether or not the returned image and beam should be normalized such that the beam peaks at a value of 1.0 Jansky.
 *                              You normally want this to be true, but it may be interesting to check the raw values for debugging purposes.
 * @param[in] f_fft (fft_function_type): Selects FFT implementation to be used.
 *
 * @return (std::pair<arma::cx_mat, arma::cx_mat>) 2 slices: result of the iFFT on the image and beam slices generated by gridding and convolution
 */
template <typename T>
std::pair<arma::cx_mat, arma::cx_mat> image_visibilities(
    const T& kernel_creator,
    arma::cx_mat vis,
    arma::mat uvw_lambda,
    int image_size,
    double cell_size,
    int support,
    bool kernel_exact = true,
    int oversampling = 1,
    bool normalize = true,
    fft_function_type f_fft = FFTW)
{
    assert(kernel_exact || (oversampling >= 1)); // If kernel exact is false, then oversampling must be >= 1
    assert(image_size > 0);
    assert(support > 0);
    assert(cell_size > 0.0);

    // Size of a UV-grid pixel, in multiples of wavelength (lambda):
    double grid_pixel_width_lambda = (1.0 / (arc_sec_to_rad(cell_size) * image_size));
    arma::mat uvw_in_pixels = uvw_lambda / grid_pixel_width_lambda;

    arma::mat uv_in_pixels(uvw_in_pixels.n_rows, 2);
    uv_in_pixels = uvw_in_pixels.head_cols(2);

    std::pair<arma::cx_mat, arma::cx_mat> result = convolve_to_grid(kernel_creator, support, image_size, uv_in_pixels, vis, kernel_exact, oversampling);

    arma::cx_mat shifted_image = fftshift(result.first, false);
    arma::cx_mat shifted_beam = fftshift(result.second, false);

    arma::cx_mat fft_result_image;
    arma::cx_mat fft_result_beam;

    switch (f_fft) {
    case FFTW:
        // FFTW implementation
        fft_result_image = fftshift(fft_fftw(shifted_image, true));
        fft_result_beam = fftshift(fft_fftw(shifted_beam, true));
        break;
    case ARMAFFT:
        // Armadillo implementation
        fft_result_image = fftshift(fft_arma(shifted_image, true));
        fft_result_beam = fftshift(fft_arma(shifted_beam, true));
        break;
    default:
        assert(0);
    }

    // Normalize image and beam such that the beam peaks at a value of 1.0 Jansky.
    if (normalize == true) {
        double beam_max = arma::real(fft_result_beam).max();

        // Use cblas for better performance
        uint n_elem = fft_result_beam.n_elem;
        cblas_zdscal(n_elem, 1 / beam_max, fft_result_beam.memptr(), 1); // Equivalent to: fft_result_beam /= beam_max;
        n_elem = fft_result_image.n_elem;
        cblas_zdscal(n_elem, 1 / beam_max, fft_result_image.memptr(), 1); // Equivalent to: fft_result_image /= beam_max;
    }

    return std::make_pair(std::move(fft_result_image), std::move(fft_result_beam));
}
}
#endif /* IMAGER_H */
